title: Lexicon Vooronderzoek
description: Een lexicon voor onderzoek
theme: minima
markdown: kramdown

# Zorgt dat GitHub Pages ook .md-bestanden buiten de root (zoals termen/*.md) meebouwt
include:
  - termen
